apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: netshop/email:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50052
              name: grpc
          env:
            - name: EMAIL_GRPC_ADDR
              value: ":50052"
          readinessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50052
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app: email
  ports:
    - name: grpc
      port: 50052
      targetPort: 50052
