apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netshop-frontend
spec:
  ingressClassName: nginx
  rules:
    - host: netshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
